services:

  backend:
    build: ./backend
    container_name: oil-spill-fastapi
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: oil-spill-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend